### PR TITLE
Bump apex-parser from 4.3.1 to 4.4.0

### PR DESCRIPTION
**Pull request by adangel**
Just updates apex-parser to the latest version

See https://github.com/apex-dev-tools/apex-parser/releases/tag/v4.4.0 for the changes.

This time, there is nothing special, as we don't parse SOSL/SOQL (yet).

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by aaronhurst-google — APPROVED** [review]
LGTM

**Comment by adangel** [comment]
Hi @aaronhurst-google , thanks for merging!

When would you be able to push a new release? We'd like to use the new version for PMD to fix a couple of parser issues and for that we need this new version (see https://github.com/pmd/pmd/pull/5327).

**Comment by adangel** [comment]
@aaronhurst-google / @aaronpaulhurst Ping :smile: 
Is there anything we can help with?

**Comment by aaronpaulhurst** [comment]
ah, sorry, got distracted by the holidays.
i kicked off the new build, and should be releasing it tomorrow morning.

**Comment by adangel** [comment]
Thanks!

**Pull request merged**
